# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dhruv Jaiswal
tagline:          'An engineer, logician and a problem solver'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://github.com/CobaltIII
baseurl:          /

author:
  name:           'Dhruv Jaiswal'
  url:            https://github.com/CobaltIII

paginate:         5

github:
  repo:           https://github.com/poole/hyde
