# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dhruv Jaiswal
tagline:          'An engineer, logician and a problem solver'
description:      'An engineer, logician and a problem solver. Currently studying in IIIT Delhi pursuing a degree in Computer Science Engineering. While dabbling in everything from math to economics and a little bit of everything.'
url:              https://github.com/CobaltIII
baseurl:          https://github.com/CobaltIII

author:
  name:           'Dhruv Jaiswal'
  url:            https://github.com/CobaltIII

paginate:         5

github:
  repo:           https://github.com/poole/hyde
